name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'reports/**'
    paths:
      - 'src/qn/**'
      - 'scripts/**'
      - 'tests/**'
      - 'Makefile'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'reports/**'
    paths:
      - 'src/qn/**'
      - 'scripts/**'
      - 'tests/**'
      - 'Makefile'
  workflow_dispatch:
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 black
      - run: flake8 .
      - run: black --check .
      # optional notebook lint:
      # - run: |
      #     pip install nbqa
      #     nbqa flake8 .
      #     nbqa black --check .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - run: pytest --cov=src/qn --cov-report=xml
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}-${{ github.sha }}
          path: coverage.xml

  pipeline:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Verify reproducible pipeline
        run: make all
      - name: Upload processed tables
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: processed-${{ github.sha }}
          path: |
            data/processed/**
            !**/*.tmp
      - name: Upload figures
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: figures-${{ github.sha }}
          path: figures/**