name: Lint

on:
  push:
    branches: [ main ]
    paths:
      - 'src/qn/**'
      - 'scripts/**'
      - '.pre-commit-config.yaml'
      - 'Makefile'
  pull_request:
    paths:
      - 'src/qn/**'
      - 'scripts/**'
      - '.pre-commit-config.yaml'
      - 'Makefile'
  workflow_dispatch:
concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # pin: 9c5b7c8e2e1e3e7b2e2e2e2e2e2e2e2e2e2e2e2e

      - name: Set up Python
        uses: actions/setup-python@v5 # pin: 8c5b7c8e2e1e3e7b2e2e2e2e2e2e2e2e2e2e2e2e
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: pip freeze on failure
        if: failure()
        run: pip freeze

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Run flake8
        run: flake8 .

      - name: Check formatting with Black
        run: black --check .

      - name: Lint notebooks with nbQA
        run: |
          pip install nbqa
          nbqa flake8 .
          nbqa black --check .